apiVersion: apps/v1
kind: Deployment
metadata:
  name: celzeyflask
  namespace: celzey9
  labels:
    app: celzeyflask
spec:
  selector:
    matchLabels:
      app: celzeyflask
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: celzeyflask
    spec:
      containers:
        - name: celzeyflask
          image: celzey9/flask_app_new
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
            limits:
              cpu: 100m
              memory: 100Mi
          ports:
            - containerPort: 5000
              name: celzeyflask
          imagePullPolicy: Always
      restartPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name: celzeyflask
  namespace: celzey9
spec:
  selector:
    app: celzeyflask
  type: LoadBalancer
  sessionAffinity: None
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800
  ports:
    - name: celzeyflask
      protocol: TCP
      port: 80
      targetPort: 5000
