apiVersion: apps/v1
kind: Deployment
metadata:
  name: celzey_flaskcontainer
  namespace: celzey9
  labels:
    app: celzey_flaskcontainer
spec:
  selector:
    matchLabels:
      app: celzey_flaskcontainer
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: celzey_flaskcontainer
    spec:
      containers:
        - name: celzey_flaskcontainer
          image: celzey9/flask_app_new
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
            limits:
              cpu: 100m
              memory: 100Mi
          ports:
            - containerPort: 5000
              name: celzey_flaskcontainer
          imagePullPolicy: Always
      restartPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name: celzey_flaskcontainer
  namespace: celzey9
spec:
  selector:
    app: celzey_flaskcontainer
  type: LoadBalancer
  sessionAffinity: None
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800
  ports:
    - name: celzey_flaskcontainer
      protocol: TCP
      port: 80
      targetPort: 5000
